import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./(components)/sidebar/Sidebar";
import Navbar from "./(components)/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Car Rental Web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex min-h-screen`}>
        <aside className="hidden md:block md:w-3/20 lg:w-1/6 lg:max-h-screen">
          {/* Sidebar content */}
          <Sidebar />
        </aside>
        <main className="flex-grow w-full md:w-17/20 lg:w-5/6 bg-gray-200 ">
          <Navbar />
          {/* Main content */}
          <div className="px-6 overflow-y-auto">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
